// AUTO-GENERATED by scripts/prepare-images.mjs — do not edit by hand.
// Intrinsic dimensions + base64 LQIP placeholders for every site image.

export type ImageAsset = { src: string; width: number; height: number; blurDataURL: string };

export const IMAGE_ASSETS = {
  'mamu-crane-service-hydra-crane-lifting-concrete-slab-kurukshetra': {
    src: '/images/mamu-crane-service-hydra-crane-lifting-concrete-slab-kurukshetra.webp',
    width: 1672,
    height: 941,
    blurDataURL:
      'data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoUAAsAPwFssE+rJiSiMAgBYCAJQBdgBDd4Eg9UEFQvAAD+7o/sR1GjWvpkX/AxzhR4daoAZyu4a9wpUqqdTNszwz5yZTebXggqXpQ6yhF6UR+QE9d1bRAA',
  },
  'crane-service-construction-site-pipli-kurukshetra': {
    src: '/images/crane-service-construction-site-pipli-kurukshetra.webp',
    width: 2048,
    height: 768,
    blurDataURL:
      'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQBACdASoUAAgAPwForE6rJaQiMAgBYCAJZACdMoACj8nPUq3fMcR0AAD+2ftnwB750eKG9/Dr12+WY3qIwtnhbMoItMtU3IrEV6qv1zQrJ4q24beGAPx+2uwKNfX2nIEQEHMIuLGteiI5cvQYAA==',
  },
  'hydra-crane-on-rent-construction-site-kurukshetra': {
    src: '/images/hydra-crane-on-rent-construction-site-kurukshetra.webp',
    width: 1671,
    height: 941,
    blurDataURL:
      'data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQAwCdASoUAAsAPwFqrU8rJiQiMAgBYCAJZgCdABuKYcBC4zsZrAAA/uZ2tH79s07aSyW9ofyTyjZQknz7v6g/dmCz9qeXXTvS72V+94p+PkNkbRVxoVmG+A5VYroaWqeLtLa2o6gSKgAA',
  },
  'mamu-crane-service-safety-helmet-site-drawings': {
    src: '/images/mamu-crane-service-safety-helmet-site-drawings.webp',
    width: 820,
    height: 388,
    blurDataURL:
      'data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAwCdASoUAAkAPwFqrE6rJiQiMAgBYCAJYgCsOUAARUP6YqAAE4AA/tqmOMaXuTQtjysHMutkd2mbjBHWLcnIsg3T6uqC4TyAcShDyVRWGfzWIl6Z9JmnOOlnBFRRAAAAAA==',
  },
  'construction-crew-at-crane-lifting-site-kurukshetra': {
    src: '/images/construction-crew-at-crane-lifting-site-kurukshetra.webp',
    width: 560,
    height: 330,
    blurDataURL:
      'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADwAwCdASoUAAwAPwForE6rJiQiMAgBYCAJYgCdEf/gHc2lCB8BCRcYAP1wbv3KY6oKu9pIUQ1TH44+MVNhKJaYfv/a5V6HF8k++vf8rIAFsKJFrZ7l69kV9s1l74lGrhxg+uuIlKT52vkL5rcAM+wl3qg6mVHBQuJ0SBNXLgA=',
  },
  'mobile-crane-boom-against-city-skyline-haryana': {
    src: '/images/mobile-crane-boom-against-city-skyline-haryana.webp',
    width: 928,
    height: 768,
    blurDataURL:
      'data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAABQBQCdASoUABEAPwFwrFGrJiQiqA1RYCAJYgC7MzQ5j8i4AApqlhLPa4GjeZcRSyszUIgA/rpqHsj+o2nm3sTgzYnjylmE81ELBboAUtJjNsXlDJk45befwkwoOKldvRoI+yjgpR7KxPD8NSJhIXBN0JEEi2FSroXpA18EIpbCTX7ITOoEWof2xlck/sBBRzfRw+2EjpAo3n0gxSV7VuTIAAA=',
  },
  'crane-hook-block-lifting-precast-concrete-slab': {
    src: '/images/crane-hook-block-lifting-precast-concrete-slab.webp',
    width: 520,
    height: 450,
    blurDataURL:
      'data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAACwBACdASoUABEAPwFysVIrJqSiqAqpYCAJYgCdABESUk5Voi2F0qIFDr/2sn1gAP7oz3vKipjXS/rCuHQ1mpOCcbJJvKImTpBDtWQ9WiT8F89gWQXn8GYnmYZN9wMIGfbGmzFpEJKKhx63fQQc/ip3+BT/gxLBlurs8E3jenL7gAAA',
  },
  'hydra-crane-boom-and-hook-close-up-kurukshetra': {
    src: '/images/hydra-crane-boom-and-hook-close-up-kurukshetra.webp',
    width: 700,
    height: 500,
    blurDataURL:
      'data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAQBQCdASoUAA4APwFqrE8rJiQiMAgBYCAJbACdMoR3JoM4DFwLH/Al4LY0y93gRHtQAP6sktyGv7A4C/hUCU9VtUh9vfGts70pwJxH/JItETMlirjEsZZB1j1jD8Vsz/fByEFWPQN4kb8K7IeVyqgrd7XqrX8m4IUA6luknkCu0hpwYIRF8bBYrxdLWG2FJZT+IAAA',
  },
  'hydra-crane-operator-cabin-haryana': {
    src: '/images/hydra-crane-operator-cabin-haryana.webp',
    width: 560,
    height: 420,
    blurDataURL:
      'data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACQBACdASoUAA8APwForE6rJaQiMAgBYCAJbACdMoGv/l2ALn1I8IXzzUHRH5AA/mZ+63yvqUfJ3Bs6LWpe9Z6/5ukwJvDJmaFp0JhJAEq463mZjqFFYZtLV5vXtVaXQOI4d2PaIc2iPG+l2KspK6hQcr5H5dLFviFKePPoMfo5fKYHjYln5GpJlC8AAA==',
  },
  'hydra-crane-on-hire-vertical-boom-kurukshetra': {
    src: '/images/hydra-crane-on-hire-vertical-boom-kurukshetra.webp',
    width: 560,
    height: 800,
    blurDataURL:
      'data:image/webp;base64,UklGRtoAAABXRUJQVlA4IM4AAADwBQCdASoUAB0APwF0rlArJyQisBgIAWAgCWwAnTKEf3LTMWYANm3Fvp9AGYADdFC1wKjUru/DIAD+F+oscMn6iBlQiCgMs6xnTQbM1U1P3Y1DQTmHt+FYNgnylnfV6gVyc3BCShwPqBDX6TtI0pFjWBSEyVB3WB1qeCJG+LKfQypgZip34hxtfdHwVt1EVT1lhH66hjbik29l5KoFZEhoY5DpDEYyEDdEOa6IQrM2jzByIH2Go5gmjcRzLT8XrqquxIDjf8DvzZNkloAAAA==',
  },
} as const satisfies Record<string, ImageAsset>;

export type ImageKey = keyof typeof IMAGE_ASSETS;
