/**
 * Derives the site's optimised image set from the original Mamu Crane Service photographs.
 * Run with: node scripts/prepare-images.mjs
 */
import sharp from 'sharp';
import { mkdir, writeFile } from 'node:fs/promises';

const SRC = 'assets/originals/';
const OUT = 'public/images/';

const SITE = SRC + '02-construction-site-panorama.png';        // 2048x768
const HERO = SRC + '01-hero-hydra-crane-lifting-slab.png';     // 1672x941, branded hydra at dusk
const HYDRA = SRC + '03-hydra-crane-under-flyover.png';        // 1671x941, orange hydra under flyover

/** @type {{name:string, src:string, crop?:{left:number,top:number,width:number,height:number}, width?:number, quality?:number}[]} */
const jobs = [
  // --- primary full-frame images ---
  { name: 'mamu-crane-service-hydra-crane-lifting-concrete-slab-kurukshetra', src: HERO, quality: 82 },
  { name: 'crane-service-construction-site-pipli-kurukshetra', src: SITE, quality: 80 },
  { name: 'hydra-crane-on-rent-construction-site-kurukshetra', src: HYDRA, quality: 80 },

  // --- authentic crops (no stretching, equipment kept intact) ---
  { name: 'mamu-crane-service-safety-helmet-site-drawings', src: SITE, crop: { left: 60, top: 380, width: 820, height: 388 } },
  { name: 'construction-crew-at-crane-lifting-site-kurukshetra', src: SITE, crop: { left: 480, top: 330, width: 560, height: 330 } },
  { name: 'mobile-crane-boom-against-city-skyline-haryana', src: SITE, crop: { left: 1120, top: 0, width: 928, height: 768 } },
  { name: 'crane-hook-block-lifting-precast-concrete-slab', src: HERO, crop: { left: 520, top: 200, width: 520, height: 450 } },
  { name: 'hydra-crane-boom-and-hook-close-up-kurukshetra', src: HYDRA, crop: { left: 260, top: 60, width: 700, height: 500 } },
  { name: 'hydra-crane-operator-cabin-haryana', src: HYDRA, crop: { left: 1080, top: 380, width: 560, height: 420 } },
  { name: 'hydra-crane-on-hire-vertical-boom-kurukshetra', src: HYDRA, crop: { left: 600, top: 60, width: 560, height: 800 } },
];

await mkdir(OUT, { recursive: true });

const blur = {};
const meta = {};

for (const job of jobs) {
  let pipe = sharp(job.src);
  if (job.crop) pipe = pipe.extract(job.crop);
  if (job.width) pipe = pipe.resize({ width: job.width, withoutEnlargement: true });

  const buf = await pipe.webp({ quality: job.quality ?? 78, effort: 6 }).toBuffer();
  await writeFile(`${OUT}${job.name}.webp`, buf);

  const m = await sharp(buf).metadata();
  meta[job.name] = { width: m.width, height: m.height };

  // tiny LQIP used as the blur placeholder
  let tinyPipe = sharp(job.src);
  if (job.crop) tinyPipe = tinyPipe.extract(job.crop);
  const tiny = await tinyPipe.resize({ width: 20 }).webp({ quality: 35 }).toBuffer();
  blur[job.name] = `data:image/webp;base64,${tiny.toString('base64')}`;

  console.log(`${job.name}.webp  ${m.width}x${m.height}  ${(buf.length / 1024).toFixed(0)}KB`);
}

const ts = `// AUTO-GENERATED by scripts/prepare-images.mjs — do not edit by hand.
// Intrinsic dimensions + base64 LQIP placeholders for every site image.

export type ImageAsset = { src: string; width: number; height: number; blurDataURL: string };

export const IMAGE_ASSETS = {
${Object.keys(meta)
  .map(
    (k) =>
      `  '${k}': {\n    src: '/images/${k}.webp',\n    width: ${meta[k].width},\n    height: ${meta[k].height},\n    blurDataURL:\n      '${blur[k]}',\n  },`,
  )
  .join('\n')}
} as const satisfies Record<string, ImageAsset>;

export type ImageKey = keyof typeof IMAGE_ASSETS;
`;

await mkdir('lib', { recursive: true });
await writeFile('lib/image-assets.ts', ts);
console.log('\nWrote lib/image-assets.ts');
